version: '3.8'

services:
  backend:
    build: .
    container_name: backend-app
    ports:
      - "5009:5009"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - JWT_SECRET=${JWT_SECRET}
      - EXPIRES_IN=${EXPIRES_IN}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN}
      - RESET_PASS_TOKEN=${RESET_PASS_TOKEN}
      - RESET_PASS_TOKEN_EXPIRES_IN=${RESET_PASS_TOKEN_EXPIRES_IN}
      - RESET_PASS_LINK=${RESET_PASS_LINK}
      - EMAIL=${EMAIL}
      - APP_PASS=${APP_PASS}
      - DO_SPACE_ENDPOINT=${DO_SPACE_ENDPOINT}
      - DO_SPACE_ORIGIN_ENDPOINT=${DO_SPACE_ORIGIN_ENDPOINT}
      - DO_SPACE_ACCESS_KEY=${DO_SPACE_ACCESS_KEY}
      - DO_SPACE_SECRET_KEY=${DO_SPACE_SECRET_KEY}
      - DO_SPACE_BUCKET=${DO_SPACE_BUCKET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - ENVIRONMENT_VARIABLE=${ENVIRONMENT_VARIABLE}
    env_file:
      - .env
